stages:
  - pre-build
  - test
  - build
  - deploy

image: node:14

pre-build:
  stage: pre-build
  dependencies: 
    - install
  script: 
    - npm install

build:
  stage: build
  dependencies: 
    - install
  script:
    - npm run build
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - when: on_success

test:
  stage: test
  dependencies: 
    - install
    - pre-build
    - build
  script: 
    - npm install
    - npm run test
    - npm run prettier
    - npm run lint

deploy:
  stage: deploy
  dependencies:
    - install
    - build
  script:
    - npx netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - when: on_success

